LABEL cb1-batocera-poc
  LINUX /boot/linux
  INITRD /boot/initrd.lz4
  FDT /boot/sun50i-h616-bigtreetech-cb1-batocera.dtb
  APPEND initrd=/boot/initrd.lz4 label=BATOCERA rootwait console=ttyS0,115200 loglevel=7 ignore_loglevel
